// Generated by jextract

package se.addiva.nalabs;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor analyzeRequirements$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle analyzeRequirements$MH = RuntimeHelper.downcallHandle(
        "analyzeRequirements",
        constants$0.analyzeRequirements$FUNC
    );
}


