// Generated by jextract

package se.addiva.nalabs;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor getHelloWorld$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle getHelloWorld$MH = RuntimeHelper.downcallHandle(
        "getHelloWorld",
        constants$0.getHelloWorld$FUNC
    );
    static final FunctionDescriptor sqrt$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle sqrt$MH = RuntimeHelper.downcallHandle(
        "sqrt",
        constants$0.sqrt$FUNC
    );
}


